### ISSUE TITLE
ERROR: Command errored out with exit status 10: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by vikiaiteam** [TheWeirdDev/PacktPub-Video-Downloader#3]
C:\Windows\System32>cd C:\PacktPub-Video-Downloader-master

C:\PacktPub-Video-Downloader-master>pip install --user pvdl
Collecting pvdl
  Using cached https://files.pythonhosted.org/packages/92/c7/c5b2c80bff7c2f6d8504cd174f738521e50cadbcfaa5056bbd65e928b6d1/pvdl-0.8.1.tar.gz
Collecting tqdm
  Using cached https://files.pythonhosted.org/packages/8c/c3/d049cf3fb31094ee045ec1ee29fffac218c91e82c8838c49ab4c3e52627b/tqdm-4.41.0-py2.py3-none-any.whl
Requirement already satisfied: requests in c:\python38\lib\site-packages (from pvdl) (2.22.0)
Collecting pycurl
  Using cached https://files.pythonhosted.org/packages/ac/b3/0f3979633b7890bab6098d84c84467030b807a1e2b31f5d30103af5a71ca/pycurl-7.43.0.3.tar.gz
    ERROR: Command errored out with exit status 10:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pf\\AppData\\Local\\Temp\\pip-install-cbwmrfxz\\pycurl\\setup.py'"'"'; __file__='"'"'C:\\Users\\SF\\
AppData\\Local\\Temp\\pip-install-cbwmrfxz\\pycurl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__
, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\SF\AppData\Local\Temp\pip-install-cbwmrfxz\pycurl\pip-egg-info'
         cwd: C:\Users\pf\AppData\Local\Temp\pip-install-cbwmrfxz\pycurl\
    Complete output (1 lines):
    Please specify --curl-dir=/path/to/built/libcurl
    ----------------------------------------
ERROR: Command errored out with exit status 10: python setup.py egg_info Check the logs for full command output.

**Comment by TheWeirdDev** [comment]
You need to install pycurl for windows before installing pvdl.

This tutorial might help: https://stackoverflow.com/questions/53492993/pycurl-installation-on-python-3-7-0-windows-10
