### ISSUE TITLE
Recaptcha 

### ISSUE THREAD

**Issue by ajsb85** [TheWeirdDev/PacktPub-Video-Downloader#5]
Error: The recaptcha solution is missing.

**Comment by TheWeirdDev** [comment]
I can't bypass the captcha but you can easily solve it yourself. Just open the packt website and go to a page that has captcha (for example the free learning page) and solve the captcha. Then go back to the script and run it again. It won't give you an error this time.

**Comment by ajsb85** [comment]
Salam @TheWeirdDev 
Seems it is mandatory always the recaptcha.
Could you authenticate with session tokens instead the password?

**Comment by TheWeirdDev** [comment]
Salam.
This script was written a long time ago. I remember that solving the captcha manually would temporarily disable recaptcha.

Unfortunately I don't have a Packt subscription anymore and I can't work on this code. I doubt using token instead of password will change anything.
