### ISSUE TITLE
error setting certificate verify locations:

### ISSUE THREAD

**Issue by dragoneye65** [TheWeirdDev/PacktPub-Video-Downloader#7]
./pvdl.py -u ...   (etc...)
It connects and is about to download when this error happens:
Any idea how I can solve this?

"
You have a valid Subscription

Chapter 1/24 (3 videos): Introduction

01-Introduction: 0.00B [00:00, ?B/s]
(77, 'error setting certificate verify locations:\n  CAfile: /etc/pki/tls/certs/ca-bundle.crt\n  CApath: none')
"

**Comment by TheWeirdDev** [comment]
install/upgrade the package `ca-certificates` using your Linux distro's package manager and try again

**Comment by dragoneye65** [comment]
![packtpub crypt test](https://github.com/TheWeirdDev/PacktPub-Video-Downloader/assets/4040093/c7e4aed2-bb33-408c-879a-301cf0c48309)
The certs seams to be fine 🤔

**Comment by dragoneye65** [comment]
Think I found the problem '/etc/pki/tls/certs/ca-bundle.crt': No such file or directory

**Comment by dragoneye65** [comment]
![image](https://github.com/TheWeirdDev/PacktPub-Video-Downloader/assets/4040093/c141ffb0-a164-439c-a827-9b3f32eb30b3)
It seams the error is generated by pycurl,  and never gets past c.perform()
I testet curl from terminal and it can get https sites.  i.e  curl https://www.google.com
Any ideas? 😊

**Comment by dragoneye65** [comment]
Solution:
1. make the directories '/etc/pki/tls/certs/' with the command: ' mkdir -p /etc/pki/tls/certs'
2. make a symlink to '/etc/ssl/certs/ca-certificates.crt' with the command: 'ln -s  /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt'

And off you go. 🥳

"OSError: [Errno 28] No space left on device"
And make sure you have enough space on your drive  😁
